import { ReactNode } from "react"
import './global.css'
import { Metadata } from "next"







export const metadata: Metadata = {
    title: 'NextOP',
    description: 'Generated by create nextop app',
    icons: 'favicon.ico'
}



export default function RootLayout({
    children
}: {
    children: ReactNode
}) {

    return (
        <html>
            <body>
                {children}
            </body>
        </html>
    )
}